name: algo_practice
channels:
  - defaults
dependencies:
  - notebook
  - numpy[version='>=1.23.0']
  - scipy[version='>=1.9.0']
  - pip
  - plotly
  - opencv
  - pandas[version='>=1.4.0']
  - jupyter
  - python=3.10
  - black
  - flake8
  - seaborn
  - jupyterlab
  - matplotlib[version='>=3.5.0']
  - tqdm
  - ipython
  - pytest
  - onnx[version='>=1.12.0,<2.0.0']
  - onnxslim[version='>=0.1.71']
  - onnxruntime-gpu
